// mycore-webcli/src/main/ts/app.component.ts
/*
 * This file is part of ***  M y C o R e  ***
 * See https://www.mycore.de/ for details.
 *
 * MyCoRe is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * MyCoRe is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with MyCoRe.  If not, see <http://www.gnu.org/licenses/>.
 */

import { Component, ViewChild } from '@angular/core';
import { WebCliCommandsComponent } from './commands/commands.component';
import { WebCliCommandInputComponent } from './command-input/command-input.component';
import { WebCliLogComponent } from './log/log.component';
import { WebCliQueueComponent } from './queue/queue.component';
import { WebCliSettingsComponent } from './settings/settings.component';
import { CommunicationService } from './service/communication.service';
import { RESTService } from './service/rest.service';

@Component({
  selector: 'webcli',
  templateUrl: 'app/app.html'
})
export class AppComponent {
  title = 'MyCoRe Web CLI2';
  refreshRunning = true;
  currentCommand: String = "";
  currentQueueLength: number = 0;
  commandHistory: string[] = [];
  activeTab: string = 'log';
  commandHistoryVisible: boolean = false;
  @ViewChild(WebCliLogComponent)
  webCliLogComponent: WebCliLogComponent;

  constructor(private _restService: RESTService,
    private _communicationService: CommunicationService) {
    this._restService.currentCommand.subscribe(
      command => {
        this.currentCommand = command;
      });

    this._restService.currentQueueLength.subscribe(
      queueLength => {
        this.currentQueueLength = queueLength;
        if (queueLength < 1) {
          this.selectTab('log');
          let logTab = <HTMLElement>document.getElementsByClassName('logTab')[0];
          if (logTab != undefined) {
            logTab.click();
          }
        }
      });
    this._communicationService.commandHistory.subscribe(
      value => {
        this.commandHistory = value.slice().reverse();
      }
    );
  }

  onClickCommandDropDown(event) {
    // if (event.target.className.indexOf("dropdown-toggle") > -1) {
    //   var maxHeight = window.innerHeight - event.target.getBoundingClientRect().bottom - 10;
    //   if (event.target.parentElement.children.length > 1 && event.target.parentElement.children[1].className == "dropdown-menu") {
    //     event.target.parentElement.children[1].style.maxHeight = maxHeight;
    //   }
    // }
  }

  clearLog() {
    this.webCliLogComponent.clearLog();
  }

  clearCommandList() {
    this._restService.clearCommandList();
  }

  setRefresh(refresh: boolean) {
    this.refreshRunning = refresh;
    if (refresh) {
      this._restService.startLogging();
    }
    else {
      this._restService.stopLogging();
    }
  }

  selectTab(tab: string) {
    this.activeTab = tab;
  }

  showCommandHistory() {
    this.commandHistoryVisible = true;
  }

  hideCommandHistory() {
    this.commandHistoryVisible = false;
  }

  onSelectCommand(com) {
    this._communicationService.setCurrentCommand(com);
    this.hideCommandHistory();
  }
}

// mycore-jobqueue/src/main/vue/jobqueue/src/App.vue
<!--
  - This file is part of ***  M y C o R e  ***
  - See https://www.mycore.de/ for details.
  -
  - MyCoRe is free software: you can redistribute it and/or modify
  - it under the terms of the GNU General Public License as published by
  - the Free Software Foundation, either version 3 of the License, or
  - (at your option) any later version.
  -
  - MyCoRe is distributed in the hope that it will be useful,
  - but WITHOUT ANY WARRANTY; without even the implied warranty of
  - MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  - GNU General Public License for more details.
  -
  - You should have received a copy of the GNU General Public License
  - along with MyCoRe.  If not, see <http://www.gnu.org/licenses/>.
  -->

<script setup lang="ts">
import {RouterView} from 'vue-router'
</script>

<template>
  <RouterView />
</template>

<style scoped>

</style>
